# Generated by Django 6.0.5 on 2026-05-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_business_problem_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot_caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='static_image',
            field=models.CharField(blank=True, help_text='Static file path relative to STATICFILES_DIRS, e.g. images/chatbot_screenshot.png', max_length=200),
        ),
    ]
